[2022-08-21 13:41:00,470] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_branch_datetime_operator.datetime_branch manual__2022-08-21T13:40:59.742434+00:00 [queued]>
[2022-08-21 13:41:00,485] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: example_branch_datetime_operator.datetime_branch manual__2022-08-21T13:40:59.742434+00:00 [queued]>
[2022-08-21 13:41:00,486] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-21 13:41:00,487] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-21 13:41:00,487] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-21 13:41:00,503] {taskinstance.py:1397} INFO - Executing <Task(BranchDateTimeOperator): datetime_branch> on 2022-08-21 13:40:59.742434+00:00
[2022-08-21 13:41:00,509] {standard_task_runner.py:52} INFO - Started process 1178 to run task
[2022-08-21 13:41:00,512] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'example_branch_datetime_operator', 'datetime_branch', 'manual__2022-08-21T13:40:59.742434+00:00', '--job-id', '17', '--raw', '--subdir', '/home/***/.local/lib/python3.7/site-packages/***/example_dags/example_branch_datetime_operator.py', '--cfg-path', '/tmp/tmpqs24nhcv', '--error-file', '/tmp/tmpciv3deca']
[2022-08-21 13:41:00,513] {standard_task_runner.py:80} INFO - Job 17: Subtask datetime_branch
[2022-08-21 13:41:00,576] {task_command.py:371} INFO - Running <TaskInstance: example_branch_datetime_operator.datetime_branch manual__2022-08-21T13:40:59.742434+00:00 [running]> on host 9be3abb2dacb
[2022-08-21 13:41:00,678] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_branch_datetime_operator
AIRFLOW_CTX_TASK_ID=datetime_branch
AIRFLOW_CTX_EXECUTION_DATE=2022-08-21T13:40:59.742434+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-21T13:40:59.742434+00:00
[2022-08-21 13:41:00,679] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/branch.py", line 52, in execute
    branches_to_execute = self.choose_branch(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/datetime.py", line 85, in choose_branch
    if upper is not None and upper < now:
TypeError: can't compare offset-naive and offset-aware datetimes
[2022-08-21 13:41:00,697] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=example_branch_datetime_operator, task_id=datetime_branch, execution_date=20220821T134059, start_date=20220821T134100, end_date=20220821T134100
[2022-08-21 13:41:00,714] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task datetime_branch (can't compare offset-naive and offset-aware datetimes; 1178)
[2022-08-21 13:41:00,764] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-21 13:41:00,813] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
